
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.src.sintactico;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int string = 4;
  public static final int op_logical = 7;
  public static final int number = 3;
  public static final int inst_main = 28;
  public static final int constant = 18;
  public static final int instr_read = 19;
  public static final int inst_elif = 13;
  public static final int two_points = 27;
  public static final int lbracket = 23;
  public static final int semicolon = 25;
  public static final int inst_function = 16;
  public static final int op_assig = 11;
  public static final int op_logical_not = 8;
  public static final int bool = 5;
  public static final int inst_return = 17;
  public static final int EOF = 0;
  public static final int inst_if = 12;
  public static final int id = 2;
  public static final int inst_else = 14;
  public static final int rparen = 22;
  public static final int error = 1;
  public static final int op_arithmetical_c = 9;
  public static final int rbracket = 24;
  public static final int op_arithmetical_b = 10;
  public static final int instr_print = 20;
  public static final int op_relational = 6;
  public static final int lparen = 21;
  public static final int comma = 26;
  public static final int inst_while = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "number",
  "string",
  "bool",
  "op_relational",
  "op_logical",
  "op_logical_not",
  "op_arithmetical_c",
  "op_arithmetical_b",
  "op_assig",
  "inst_if",
  "inst_elif",
  "inst_else",
  "inst_while",
  "inst_function",
  "inst_return",
  "constant",
  "instr_read",
  "instr_print",
  "lparen",
  "rparen",
  "lbracket",
  "rbracket",
  "semicolon",
  "comma",
  "two_points",
  "inst_main"
  };
}

